%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters.
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.f: 5.9899966570909692e+002
Camera.cu: 4.6145029449462891e+002
Camera.cv: 2.1999653625488281e+002

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

# stereo baseline times f  unit:m
Camera.b: 0.06099370081684167654981256630735

